from ..models.moyoyo import MoYoYoTTSConfig

# 基础预训练模型文件映射
BASE_PRETRAINED_FILES = {
    'chinese-hubert-base/config.json': 'chinese-hubert-base/config.json',
    'chinese-hubert-base/preprocessor_config.json': 'chinese-hubert-base/preprocessor_config.json',
    'chinese-hubert-base/pytorch_model.bin': 'chinese-hubert-base/pytorch_model.bin',
    'chinese-roberta-wwm-ext-large/config.json': 'chinese-roberta-wwm-ext-large/config.json',
    'chinese-roberta-wwm-ext-large/pytorch_model.bin': 'chinese-roberta-wwm-ext-large/pytorch_model.bin',
    'chinese-roberta-wwm-ext-large/tokenizer.json': 'chinese-roberta-wwm-ext-large/tokenizer.json',
}

# MoYoYo TTS配置列表
MOYOYO_TTS_CONFIGS = [
    # ================================ 中文 ================================
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Doubao',
        'priority': 10,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/doubao.png',
        'description': '豆包是MoYoYo的虚拟助手，能陪你聊天解闷，不管是聊生活趣事，知识科普还是帮你出主意，我都在行哦。',
        'file_size': '240M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/doubao_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/doubao_best_sovits.pth',
            'reference_audio': 'ref_audios/doubao_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "我叫豆包呀，能陪你聊天解闷，不管是聊生活趣事，知识科普还是帮你出主意，我都在行哦。",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Luo Xiang',
        'priority': 8,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/luoxiang.png',
        'description': '著名法学教授罗翔的AI语音模型，具有其独特的幽默风趣和深入浅出的讲解风格，擅长用生动的比喻和案例阐述复杂的法理问题。',
        'file_size': '240M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/luoxiang_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/luoxiang_best_sovits.pth',
            'reference_audio': 'ref_audios/luoxiang_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "复杂的问题背后也许没有统一的答案，选择站在正方还是反方，其实取决于你对一系列价值判断的回答。",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Ma Baoguo',
        'priority': 6,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/mabaoguo.png',
        'description': '太极大师马保国的AI语音模型，带有其标志性的口音和语调特色，以及独特的武学理论表达方式，适合制作娱乐性内容。',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/mabaoguo_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/mabaoguo_best_sovits.pth',
            'reference_audio': 'ref_audios/mabaoguo_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "当他弄清为什么我能打出这个五连鞭，他们打不出来的时候。",
            # 'prompt_text': "",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Shen Yi',
        'priority': 7,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/shenyi.png',
        'description': '知名网络主播沈逸的AI语音模型，具有其独特的理性分析风格和富有磁性的嗓音，擅长深度解读时事和国际政治话题。',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/shenyi_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/shenyi_best_sovits.pth',
            'reference_audio': 'ref_audios/shenyi_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "这事情本身在我看来其实挺莫名的, 啊我不太可能后面有机会还去寻求一下这个解释说。",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Yang Mi',
        'priority': 9,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/yangmi.png',
        'description': '著名演员杨幂的AI语音模型，拥有其清甜动人的声线和自然流畅的表达方式，适合制作各类娱乐和时尚内容。',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/yangmi_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/yangmi_best_sovits.pth',
            'reference_audio': 'ref_audios/yangmi_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "你谁知道, 人生只有一次啊. 你怎么知道那样选, 你当下来说, 应该那样选. 为什么没那样选呢?  但你今天这样选了呀.",
            # 'prompt_text': "",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Zhou Jielun',
        'priority': 9,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/zhoujielun.png',
        'description': '华语歌王周杰伦的AI语音模型，具有其标志性的说话风格和音乐气质，带有台湾口音特色，适合音乐和创意内容制作。',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/zhoujielun_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/zhoujielun_best_sovits.pth',
            'reference_audio': 'ref_audios/zhoujielun_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "其实我我现在讲的这些奥，都是我未来成功的一些关键。",
            # 'prompt_text': "",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Ma Yun',
        'priority': 8,
        'cover_image': 'https://huggingface.co/MoYoYoTech/tone-models/resolve/main/cover/mayun.png',
        'description': '阿里巴巴创始人马云的AI语音模型，具有其富有激情的演讲风格和独特的商业洞察表达方式，适合商业和励志内容制作。',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/mayun_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/mayun_best_sovits.pth',
            'reference_audio': 'ref_audios/mayun_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "这是我们最大的希望能招聘的到人。所以今天阿里巴巴公司内部，我自己这么觉得，人才梯队的建设非常之好。",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.1,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Bai Yansong',
        'priority': 8,
        'cover_image': '',
        'description': '',
        'file_size': '241M',
        'is_chinese_voice': True,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/bys_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/bys_best_sovits.pth',
            'reference_audio': 'ref_audios/bys_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "zh",
            'prompt_text': "这一切都使年轻人觉得连自己都很难照顾，而且是贫于奔命，我还怎么去抚育下一代。",
            'prompt_lang': "zh",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.0,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },

    # ================================ 英文 ================================
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Maple',
        'priority': 6,
        'cover_image': '',
        'description': '轻松坦率',
        'file_size': '241M',
        'is_chinese_voice': False,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/maple_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/maple_best_sovits.pth',
            'reference_audio': 'ref_audios/maple_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "en",
            'prompt_text': "There was a little tea shop in a bustling village. Every morning, the owner, an elderly woman, would wake up early.",
            'prompt_lang': "en",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.0,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Cove',
        'priority': 6,
        'cover_image': '',
        'description': '沉稳直率',
        'file_size': '241M',
        'is_chinese_voice': False,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/maple_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/cove_best_sovits.pth',
            'reference_audio': 'ref_audios/cove_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "en",
            'prompt_text': "and he has a long career in the Senate representing Delaware. So both have had significant impacts on American politics and policies.",
            'prompt_lang': "en",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.0,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Juniper',
        'priority': 6,
        'cover_image': '',
        'description': '开放豁达',
        'file_size': '241M',
        'is_chinese_voice': False,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/maple_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/juniper_best_sovits.pth',
            'reference_audio': 'ref_audios/juniper_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "en",
            'prompt_text': "Tesla, which he joined in the early 2000s, is famous for its electric vehicles.",
            'prompt_lang': "en",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.0,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },
    {
        'repository': 'MoYoYoTech/tone-models',
        'character_name': 'Ellen',
        'priority': 5,
        'cover_image': '',
        'description': '美国脱口秀主持人Ellen DeGeneres的AI语音模型，具有其标志性的幽默风格和独特的表达方式，适合制作娱乐和创意内容。',
        'file_size': '241M',
        'is_chinese_voice': False,
        'model_files': {
            **BASE_PRETRAINED_FILES,
            'gpt-weights': 'GPT_weights/ellen_best_gpt.ckpt',
            'sovits-weights': 'SoVITS_weights/ellen_best_sovits.pth',
            'reference_audio': 'ref_audios/ellen_ref.wav',
        },
        'inference_parameters': {
            'text_lang': "en",
            'prompt_text': "It might serve you better to be a little less comfortable. But wherever you're listening to this book, please remember to turn off your cell phone and that the taking of flash photographs is strictly forbidden.",
            'prompt_lang': "en",
            'top_k': 5,
            'top_p': 1,
            'temperature': 1,
            'text_split_method': "cut0",
            'batch_size': 100,
            'speed_factor': 1.0,
            'split_bucket': True,
            'return_fragment': False,
            'fragment_interval': 0.07,
            'seed': 233333,
        },
    },

]


def get_moyoyo_configs() -> list[MoYoYoTTSConfig]:
    """获取所有MoYoYo TTS配置"""
    return [MoYoYoTTSConfig(**config) for config in MOYOYO_TTS_CONFIGS]
